### ISSUE TITLE
使用NewLife.Net时遇到一个问题

### ISSUE THREAD

**Issue by 5653325** [NewLifeX/NewLife.Net#2]
使用NewLife.Net时遇到一个问题
我和客户端约定，第一次请求的时候带上文件名和文件长度，然后发送文件流。现在这个Received每次都会被触发，我的本意是类似原生socket那样，我可以一直Receive，直到达到约定文件长度结束（如图）。
`while(headerBUffer.Length>size){
byte[] buff=new byte[1024];
int num=socket.Receive(buff);
if(num>0)
{
//……
}
}`
比如用户提交一个10M的文件，第一次请求的时候带上了文件名和文件长度，我现在在NewLife.Net的server.Received中没办法实现那个一直接收的动作，只能每次数据来触发一次这个事件。
这样就导致了我后面接收的不知道一开始请求的那个文件名是什么（我现在用一个静态字典来维护，觉得不是太好）

**Comment by nnhy** [comment]
你需要自己定义一种传递文件内容的协议，NewLife.Net只提供了实现协议的基础框架
