### ISSUE TITLE
RPC 的Session怎么向客户端发送数据呢。望大神指点

### ISSUE THREAD

**Issue by MarshalT** [NewLifeX/NewLife.Net#4]
![image](https://user-images.githubusercontent.com/33778588/59400124-ef57e000-8dc8-11e9-91ee-3a4825456514.png)

**Comment by pjy612** [comment]
```
//服务端的Controller 里面
IApiSession session
//调用对应客户端的接口
await session.InvokeAsync<T>("Client/xxx", new {xxx});

//客户端
ApiClient client
//同服务端一样注册Controller
client.Register<ClientController>();
```

**Comment by nnhy** [comment]
最新版 ApiServer 已经去掉了服务端向客户端发指令的功能，但是可以通过NetSession直接发送数据

**Comment by pjy612** [comment]
> 最新版 ApiServer 已经去掉了服务端向客户端发指令的功能，但是可以通过NetSession直接发送数据

ApiClient 支持异步执行吗？
有的时候需要相互Rpc...
但是 ApiServer在公网，ApiClient 在内网，ApiServer 有时候要针对性的发些任务给 连上的ApiClient执行并返回... 
大概怎么用比较好 \_(:з」∠)\_

**Comment by nnhy** [comment]
ApiClient天生就仅支持异步InvokeAsync，同步的Invoke只不过是对异步的一个包装而已。

所有需要服务端主动向客户端推送的架构设计，都可以简化为LongPull长拉模式。客户端发起请求的时候带上参数timeout，如timeout=15000，那么服务端就会while+sleep查询目标数据，如果有数据立马返回。客户端每次InvokeAsync，有数据时马上返回，没数据时最多阻塞15000ms。客户端每次Pull结束后，马上再次发起Pull，即可得到非常接近实时推送的效果。

实际上RocketMQ就是这么做的

**Comment by pjy612** [comment]
> ApiClient天生就仅支持异步InvokeAsync，同步的Invoke只不过是对异步的一个包装而已。
> 
> 所有需要服务端主动向客户端推送的架构设计，都可以简化为LongPull长拉模式。客户端发起请求的时候带上参数timeout，如timeout=15000，那么服务端就会while+sleep查询目标数据，如果有数据立马返回。客户端每次InvokeAsync，有数据时马上返回，没数据时最多阻塞15000ms。客户端每次Pull结束后，马上再次发起Pull，即可得到非常接近实时推送的效果。
> 
> 实际上RocketMQ就是这么做的

没。。。其实是说早期版本中 ApiServer发给ApiClient执行的时候，看代码好像只有同步的。
然后我对照着 加了个 异步处理的 ，但是 好像数据包会截断？

**Comment by pjy612** [comment]
> ApiClient天生就仅支持异步InvokeAsync，同步的Invoke只不过是对异步的一个包装而已。
> 
> 所有需要服务端主动向客户端推送的架构设计，都可以简化为LongPull长拉模式。客户端发起请求的时候带上参数timeout，如timeout=15000，那么服务端就会while+sleep查询目标数据，如果有数据立马返回。客户端每次InvokeAsync，有数据时马上返回，没数据时最多阻塞15000ms。客户端每次Pull结束后，马上再次发起Pull，即可得到非常接近实时推送的效果。
> 
> 实际上RocketMQ就是这么做的

emmmm 我好像懂了，是说让客户端自己去服务端轮询拿是吧。。。
因为服务器上行不高，而且并发不太清楚好不好控制。所以想要精准推送任务什么的...我去查查LongPull 是什么。谢谢大佬
