### ISSUE TITLE
WPF[NET45]  在访问 ApiServer 时会卡死，无法接收到服务端发送来的数据

### ISSUE THREAD

**Issue by carlzhu** [NewLifeX/NewLife.Net#6]
可能与wpf本身框调有关，调试源码时是有信息返回的，并未报出任何错误。

**Comment by batsword** [comment]
网络框架怎么跟wpf有关系呢

**Comment by nnhy** [comment]
经核实，该问题源自于 wpf/winform 同步调用ApiClient的异步接口所致。
解决方法有二：
1，async/await 一路到顶
2，Task.Run().Result 包装异步操作，阻断上下文传递
