### ISSUE TITLE
TCP 客户端收消息需要服务的发送两次才能接收成功

### ISSUE THREAD

**Issue by ANCB520** [NewLifeX/NewLife.Net#8]
![image](https://github.com/NewLifeX/NewLife.Net/assets/23068266/7841b948-1b87-4671-98eb-1fc7ab5d624a)
在给客户端发送信息时，发一次客户端无法收到消息，必须得发两次客户端才能收到一次消息
![image](https://github.com/NewLifeX/NewLife.Net/assets/23068266/b703e5c7-2684-4558-b2f4-25f831c4e999)

**Comment by nnhy** [comment]
从HEX来看是正常的，是不是粘包问题没处理好

**Comment by ANCB520** [comment]
应该和粘包没关系，因为测试的发送信息的频率很低，而且是第一次发送收不到，必须快速的连续发送两次才能收到一次消息，不知道什么原因，已经放弃了

**Comment by nnhy** [comment]
通过Wireshark抓包，判断服务端是否真的发了两次。这样子把问题分类到C端还是S端，再各自查代码日志

**Comment by ANCB520** [comment]
最近还发现一个问题，服务器端接收到的消息Packet，Count为0，实际上Data中是有数据的
![image](https://github.com/NewLifeX/NewLife.Net/assets/23068266/bef8c36d-0ad2-4398-92e7-231ccc0a7441)

**Comment by nnhy** [comment]
Packet是一个缓冲区Data的包装，很像后来出现的Span。
在网络库中，Packet包装的Data本质上就是网络底层的缓冲区。
Count为0，说明收到0长度数据包，Data里面的数据可能是上次的。
